on: 
  push: 
    branches: github-actions

jobs: 

  call-workflow-backend-tests:
    uses: ./.github/workflows/backendTests.yml

  call-workflow-frontend-tests:
    uses: ./.github/workflows/frontendTests.yml

  call-workflow-frontend-sonarqube:
    uses: ./.github/workflows/frontendSonarqube.yml
    secrets: inherit

  call-workflow-docker:
    needs: [call-workflow-backend-tests, call-workflow-frontend-tests, call-workflow-frontend-sonarqube]
    uses: ./.github/workflows/docker.yml
    secrets: inherit