on: 
  push: 
    branches: [main, develop, github-actions]
  pull_request:
    branches: [main, develop, github-actions]

jobs: 

  call-workflow-backend-tests:
    uses: ./.github/workflows/backendTests.yml

  call-workflow-frontend-tests:
    uses: ./.github/workflows/frontendTests.yml

  call-workflow-backend-sonarqube:
      needs: call-workflow-backend-tests
      uses: ./.github/workflows/backendSonarqube.yml
      secrets: inherit

  call-workflow-frontend-sonarqube:
    needs: call-workflow-frontend-tests
    uses: ./.github/workflows/frontendSonarqube.yml
    secrets: inherit

  call-workflow-docker:
    needs: [call-workflow-backend-tests, call-workflow-frontend-tests, 
      call-workflow-backend-sonarqube, call-workflow-frontend-sonarqube]
    uses: ./.github/workflows/docker.yml
    secrets: inherit