on:
  workflow_call:
  
jobs:

  analyse-backend-code:

    defaults:
      run:
        working-directory: ${{ github.workspace }}/back

    runs-on: ubuntu-latest

    steps:

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
        
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        # env: 
        #   working-directory: ./back
        with:
          #working-directory: ./back
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
        
      - name: Cache Maven packages
        uses: actions/cache@v4
        # env: 
        #   working-directory: ./back
        with:
          #working-directory: ./back
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Analyze backend
        env:
          #projectBaseDir: ~/back
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #working-directory: back
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Solau92_DevFS-Projet-10-Gerez-un-projet-collaboratif-en-integrant-une-demarche-CI-CD

      # - name: Analyze backend
      # uses: sonarsource/sonarcloud-github-action@v3.1.0
      # with: 
      #   # projectBaseDir: back
      #   args: >
      #     -Dsonar.organization=solau92
      #     -Dsonar.projectKey=Solau92_DevFS-Projet-10-Gerez-un-projet-collaboratif-en-integrant-une-demarche-CI-CD
      #     -Dsonar.sources=back/src/main/java
      #     -Dsonar.tests=back/src/test/java
      #     -Dsonar.java.binaries=back/target/classes
      #     -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
      #     -Dsonar.coverage.exclusions=back/target/**,back/src/test/*
      #     -Dsonar.exclusions=back/target/**
      #     -Dsonar.verbose=true
      # env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      


        ## Front 

      # - uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      # - name: Analyze frontend
      #   uses: SonarSource/sonarcloud-github-action@master
      #   with: 
      #     projectBaseDir: ./front
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - uses: actions/checkout@v4
      #   with:
      #       fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      ## Back
